default:
  target: prod
  outputs:
    prod:
      type: snowflake
      account: nnb42337.us-east-1
      user: anurag
      password: gBfWXMARUu@9
      role: accountadmin
      warehouse: compute_wh
      database: rawdata_db
      schema: demo
      threads: 4
      client_session_keep_alive: False
