name: dbt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  dbt:
    name: dbt
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dbt-core
        pip install dbt-snowflake
    
    - name: Debug Environment Variables
      env:
        SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
        SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
        SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
        SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
      run: |
        echo "SNOWFLAKE_ACCOUNT: $SNOWFLAKE_ACCOUNT"
        echo "SNOWFLAKE_USER: $SNOWFLAKE_USER"
        echo "SNOWFLAKE_ROLE: $SNOWFLAKE_ROLE"
        echo "SNOWFLAKE_WAREHOUSE: $SNOWFLAKE_WAREHOUSE"
        echo "SNOWFLAKE_DATABASE: $SNOWFLAKE_DATABASE"
        echo "SNOWFLAKE_SCHEMA: $SNOWFLAKE_SCHEMA"
    
    - name: Run dbt
      env:
        SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
        SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
        SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
      run: |
        echo "DBT_PROFILES_DIR: $PWD"
        echo "SNOWFLAKE_USER: $SNOWFLAKE_USER"
        dbt debug --profiles-dir .
        dbt deps --profiles-dir .
        dbt compile --profiles-dir .
        dbt run --profiles-dir .
        dbt test --profiles-dir .
